apiVersion: v1
kind: ResourceQuota
metadata:
  name: project7-quota
  namespace: project7-ns
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "4Gi"
    persistentvolumeclaims: "4"
    requests.storage: "20Gi"