apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: project7-ns
type: Opaque
stringData:
  mysql-root-password: rootpass123
  mysql-database: wordpress
  mysql-user: wpuser
  mysql-password: wppass123